apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: engdemo
  name: demo-deployment
spec:
  selector:
    matchLabels:
      app: engdemo
  replicas: 4 # will change this deployment to run 4 pods
  template:
    metadata:
      labels:
        app: engdemo
    spec:
      containers:
      - name: eng-demo-deployment
        image: nginx:1.14.2
        ports:
        - containerPort: 8080
